// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyURL():Promise<void>;

export function GetInitialState():Promise<main.InitialState>;

export function OpenDemo():Promise<void>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function SelectLlamaServer():Promise<string>;

export function SelectModel():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function StartAutoDownload():Promise<void>;

export function StartServer(arg1:main.ConfigDTO):Promise<void>;

export function StopServer():Promise<void>;

export function TriggerQuickTest(arg1:string):Promise<string>;
