// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyURL() {
  return window['go']['main']['App']['CopyURL']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function OpenDemo() {
  return window['go']['main']['App']['OpenDemo']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectLlamaServer() {
  return window['go']['main']['App']['SelectLlamaServer']();
}

export function SelectModel() {
  return window['go']['main']['App']['SelectModel']();
}

export function SetBackend(arg1) {
  return window['go']['main']['App']['SetBackend'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StartAutoDownload() {
  return window['go']['main']['App']['StartAutoDownload']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function TriggerQuickTest(arg1) {
  return window['go']['main']['App']['TriggerQuickTest'](arg1);
}
